playSound:
  lore:
    text:
      sound: "サウンド "
      volume: "音量 "
      pitch: "ピッチ "
    colour:
      sound: "§6"
      volume: "§6"
      pitch: "§6"
  maxVolume: 2
  maxPitch: 3
sendMessage:
  lore:
    text: "%d行目: "